
version: "3.8"
services:
    keygen: 
        build:
          context: .
          dockerfile: ./nodes/Dockerfile
        volumes:
            - ./outputs/nodes/config:/config
            - ./outputs/nodes/ms-keys:/ms-keys
            - ./outputs/nodes/blob-keys:/blob-keys
